class LinkedinSelectors:
    LINKEDIN_LOGO_ID = 'global-nav'
    USERNAME_INPUT_ID = 'session_key'
    PASSWORD_INPUT_ID = 'session_password'
    APPLY_JOB_BUTTON_SELECTOR = 'div.jobs-apply-button--top-card'
    PAGINATION_BAR_SELECTOR = 'ul.artdeco-pagination__pages > li > button'
    PAGINATION_PAGE_BUTTON_SELECTOR = 'ul.artdeco-pagination__pages > li > button'
    SEARCH_LOCATION_INPUT_SELECTOR = 'div.jobs-search-box__input--location > div > div > input'
    SEARCH_KEYWORD_INPUT_SELECTOR = 'input.jobs-search-box__keyboard-text-input'
    SEARCH_ALL_FILTER_BUTTON_SELECTOR = 'button.search-reusables__all-filters-pill-button'
    SEARCH_FILTER_DISTANCE_SLIDER_SELECTOR = 'input#distance-advanced-filter-slider'
    SEARCH_FILTER_ALL_SECTORS_SELECTOR = 'div.search-reusables__side-panel--open li.search-reusables__secondary-filters-filter'
    SEARCH_FILTER_SECTOR_ALL_CHECKBOXES_SELECTOR = 'div.search-reusables__secondary-filters-values > ul > li'
    SEARCH_FILTER_SECTOR_CHECKBOX_SELECTOR = 'label.search-reusables__value-label'
    SEARCH_APPLY_FILTER_BUTTON_SELECTOR = 'button.search-reusables__secondary-filters-show-results-button'
    CARDS_SELECTOR = 'ul.scaffold-layout__list-container > li '
    CARD_TITLE_SELECTOR = 'div.job-card-container--clickable ul.job-card-container__footer-wrapper'
    CARD_DETAILS_SELECTOR = 'div.jobs-details__main-content'
    CARD_DETAILS_JOB_TITLE_SELECTOR = 'h2.jobs-unified-top-card__job-title'
    CARD_DETAILS_COMPANY_NAME_SELECTOR = 'span.jobs-unified-top-card__subtitle-primary-grouping span.jobs-unified-top-card__company-name a'
    CARD_DETAILS_JOB_DESCRIPTION_SELECTOR = 'div.jobs-description-content__text'
    CARD_DETAILS_JOB_LOCATION_SELECTOR = 'span.jobs-unified-top-card__bullet'
    CARD_DETAILS_JOB_WORK_TYPE_SELECTOR = 'span.jobs-unified-top-card__workplace-type'
    CARD_DETAILS_JOB_SIZE_SELECTOR = 'li.jobs-unified-top-card__job-insight'

